#!/bin/sh

# The reference version of this script is maintained in:
#   kali-installer/simple-cdd/profiles/kali.postinst
#   kali-live/kali-config/common/includes.installer/kali-finish-install
#   kali-live/kali-config/common/includes.chroot/usr/lib/live/config/0031-kali-user-setup
#   kali-vm/scripts/finish-install.sh
# (sometimes with small variations)
#
# It is used in multiple places to finish configuring the target system
# and build.sh copies it where required (in the simple-cdd configuration
# and in the live-build configuration).

# Zyphor OS Custom Post Install Configurations (1)

configure_zyphor() {

    set -e

    echo "INFO: Applying Zyphor OS customizations"

    # For lightdm gtk greeter - create /desktop-base folder inside /usr/share/images/[desktop-base]

    mkdir -p /usr/share/images/desktop-base

    # create symlinks of the wallpapers and default desktop wallpapers

    ln -sf /usr/share/backgrounds/backgrounds.png /usr/share/images/desktop-base/default

    ln -sf /usr/share/backgrounds/backgrounds2.png /usr/share/images/desktop-base/default-2

    ln -sf /usr/share/backgrounds/backgrounds3.png /usr/share/images/desktop-base/default-3

    ln -sf /usr/share/backgrounds/backgrounds4.png /usr/share/images/desktop-base/default-4

    # lightdm .face symlink

    ln -sf /etc/skel/.face /etc/skel/.face.icon

    # Zyphor Custom Commands configurations - allow custom commands to be executable

    chmod +x /usr/local/bin/zyphor

    # For GRUB Bootloader - create a folder /boot/zyphor

    mkdir -p /boot/zyphor

    # copy main GRUB Bootloader splash screen

    cp /usr/share/backgrounds/zyphor-grub-bootloader-screensavers/grub-bootloader-screen-saver.png /boot/zyphor

    # rename default GRUB Bootloader Image

    mv /boot/zyphor/grub-bootloader-screen-saver.png /boot/zyphor/splash.png

    # update GRUB Bootloader Settings

    update-grub

    # plymouth - to be continue...

    # zyphor commands copy by force to /usr/local/bin - to be continue...

    # - copy first the commands/zyphor to the /usr/local/bin folder

}

# End Of Zyphor OS Custom Post Install Configurations (2)

configure_sources_list() {
    if grep -q '^deb ' /etc/apt/sources.list; then
        echo "INFO: sources.list is configured, everything is fine"
        return
    fi

    echo "INFO: sources.list is empty, setting up a default one for Kali"

    cat >/etc/apt/sources.list <<END
# See https://www.kali.org/docs/general-use/kali-linux-sources-list-repositories/
deb http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware

# Additional line for source packages
# deb-src http://http.kali.org/kali kali-rolling main contrib non-free non-free-firmware
END
    apt-get update
}

get_user_list() {
    for user in $(cd /home && ls); do
        if ! getent passwd "$user" >/dev/null; then
            echo "WARNING: user '$user' is invalid but /home/$user exists" >&2
            continue
        fi
        echo "$user"
    done
    echo "root"
}

configure_zsh() {
    if grep -q 'nozsh' /proc/cmdline; then
        echo "INFO: user opted out of zsh by default"
        return
    fi
    if [ ! -x /usr/bin/zsh ]; then
        echo "INFO: /usr/bin/zsh is not available"
        return
    fi
    for user in $(get_user_list); do
        echo "INFO: changing default shell of user '$user' to zsh"
        chsh --shell /usr/bin/zsh $user
    done
}

configure_usergroups() {
    # Ensure those groups exist
    addgroup --system kaboxer || true
    addgroup --system wireshark || true

    # adm - read access to log files
    # dialout - for serial access
    # kaboxer - for kaboxer
    # vboxsf - shared folders for virtualbox guest
    # wireshark - capture sessions in wireshark
    kali_groups="adm dialout kaboxer vboxsf wireshark"

    for user in $(get_user_list | grep -xv root); do
        echo "INFO: adding user '$user' to groups '$kali_groups'"
        for grp in $kali_groups; do
            getent group $grp >/dev/null || continue
            usermod -a -G $grp $user
        done
    done
}

pkg_installed() {
    dpkg -s "$1" 2>/dev/null | grep -q "ok installed"
}

configure_terminal() {
    while read -r desktop terminal; do
        pkg_installed kali-desktop-$desktop || continue
        echo "INFO: setting x-terminal-emulator alternative to '$terminal'"
        update-alternatives --verbose --set x-terminal-emulator /usr/bin/$terminal || true
        break
    done <<END
e17   terminology
gnome gnome-terminal.wrapper
i3    kitty
kde   konsole
lxde  lxterminal
mate  mate-terminal.wrapper
xfce  qterminal
END
}

configure_sources_list
configure_zsh
configure_usergroups
configure_terminal

# Zyphor OS Custom Post Install Configurations (2)

configure_zyphor

# End Of Zyphor OS Custom Post Install Configurations (2)
