---
sequence:
  - show:
      - welcome
      - locale
      - keyboard
      - partition
      - users
      - summary
      - install
      - finished

modules-search:
  - /usr/lib/calamares/modules
  - /usr/share/calamares/modules

branding: youros

prompt-install: true
disable-cancel: false